import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useRef } from "react";
import styled from "styled-components";
import { useSocket } from "../hooks/useSocket";

const Home: NextPage = () => {
  const ChatDisplayContainerRef = useRef<HTMLDivElement>(null);

  const {
    count,
    userName,
    onChangeNickName,
    onEnterNickName,
    onChangeChat,
    chat,
    onEnterChat,
    chatLog,
  } = useSocket();

  useEffect(() => {
    if (ChatDisplayContainerRef.current) {
      ChatDisplayContainerRef.current.scrollTop =
        ChatDisplayContainerRef.current.scrollHeight;
    }
  }, [chatLog]);

  return (
    <div>
      <Head>
        <title>채팅 테스트</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex-col items-center justify-center w-[100vw] h-[100vh] bg-slate-50">
        <Header className="text-xl flex justify-center">실습용 채팅방</Header>
        <ChatRoomContainer className="flex flex-col items-center justify-around h-1/2">
          <div>접속중인 인원: {count}</div>
          <div>당신의 닉네임: {userName}</div>
          <ChatDisplayContainer
            ref={ChatDisplayContainerRef}
            className="w-[500px] h-[500px] border-4 overflow-scroll"
          >
            {chatLog.map(({ userName: chatUserName, message }) => (
              <p key={chatUserName}>
                {chatUserName === userName ? (
                  <b>
                    {chatUserName}:{message}
                  </b>
                ) : (
                  `${chatUserName}:${message}`
                )}
                
              </p>
            ))}
          </ChatDisplayContainer>

          <ChatInputContainer>
            <input
              className="w-[100px] mr-5 p-2 border-4"
              placeholder="닉네임"
              onKeyUp={onEnterNickName}
              value={userName}
              onChange={onChangeNickName}
            />
            <input
              className="p-2 border-4"
              placeholder="내용을 입력해주세요"
              onKeyUp={onEnterChat}
              value={chat}
              onChange={onChangeChat}
            />
          </ChatInputContainer>
        </ChatRoomContainer>
      </main>
    </div>
  );
};

const Header = styled.header``;

const ChatRoomContainer = styled.div``;
const ChatDisplayContainer = styled.div`
  b {
    color: red;
  }
`;
const ChatInputContainer = styled.div``;

export default Home;
